export const TASK_STATUSES = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  IN_REVIEW: "IN_REVIEW",
  DONE: "DONE",
  CANCELLED: "CANCELLED",
} as const;

export type TaskStatus = (typeof TASK_STATUSES)[keyof typeof TASK_STATUSES];

export const TASK_PRIORITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
} as const;

export type TaskPriority = (typeof TASK_PRIORITIES)[keyof typeof TASK_PRIORITIES];

/** Allowed status transitions for workflow validation */
export const TASK_STATUS_TRANSITIONS: Record<TaskStatus, TaskStatus[]> = {
  [TASK_STATUSES.TODO]: [TASK_STATUSES.IN_PROGRESS, TASK_STATUSES.CANCELLED],
  [TASK_STATUSES.IN_PROGRESS]: [
    TASK_STATUSES.TODO,
    TASK_STATUSES.IN_REVIEW,
    TASK_STATUSES.DONE,
    TASK_STATUSES.CANCELLED,
  ],
  [TASK_STATUSES.IN_REVIEW]: [
    TASK_STATUSES.IN_PROGRESS,
    TASK_STATUSES.DONE,
    TASK_STATUSES.CANCELLED,
  ],
  [TASK_STATUSES.DONE]: [TASK_STATUSES.IN_PROGRESS, TASK_STATUSES.TODO],
  [TASK_STATUSES.CANCELLED]: [TASK_STATUSES.TODO],
};
